#!/usr/bin/env bash
# Issue one pool-scoped api-worker key per simulated site and write the env file
# that site's container boots from. Idempotent: a key that already exists is
# rotated, so re-running never leaves a stale secret on disk. Restart the site
# containers afterwards (docker compose -f docker-compose.sites.yml up -d).
#
#   PRIMEFLOW_URL       server base URL     (default http://localhost:8085)
#   PRIMEFLOW_ADMIN     operator email      (default admin@primeflow.local)
#   PRIMEFLOW_PASSWORD  operator password   (default primeflow-admin)
#   SITES               space-separated     (default "site-a site-b site-c")
set -euo pipefail

SERVER="${PRIMEFLOW_URL:-http://localhost:8085}"
EMAIL="${PRIMEFLOW_ADMIN:-admin@primeflow.local}"
PASSWORD="${PRIMEFLOW_PASSWORD:-primeflow-admin}"
SITES="${SITES:-site-a site-b site-c}"
DIR="$(cd "$(dirname "$0")" && pwd)"

command -v jq >/dev/null || { echo "jq is required" >&2; exit 1; }

JAR="$(mktemp)"
trap 'rm -f "$JAR"' EXIT

curl -sfS -c "$JAR" -X POST "$SERVER/api/v1/auth/login" -H 'Content-Type: application/json' \
  -d "$(jq -cn --arg e "$EMAIL" --arg p "$PASSWORD" '{email:$e,password:$p}')" >/dev/null
CSRF="$(awk '$6=="pf_csrf"{print $7}' "$JAR")"

api() { # method path [json-body]
  curl -sfS -b "$JAR" -X "$1" "$SERVER/api/v1$2" \
    -H 'Content-Type: application/json' -H "X-CSRF-Token: $CSRF" ${3:+-d "$3"}
}

for site in $SITES; do
  # The pool. Upserting only name and owner leaves an existing pool's
  # concurrency and autoscale settings alone.
  api POST /queues "$(jq -cn --arg s "$site" '{name:$s, owner:$s}')" >/dev/null

  name="$site-worker"
  # The list is JSON null when no key of this role exists yet.
  id="$(api GET "/api-keys?role=api-worker" | jq -r --arg n "$name" '(. // []) | .[] | select(.name==$n) | .id' | head -n1)"
  if [ -n "$id" ]; then
    secret="$(api POST "/api-keys/$id/rotate" | jq -r .secret)"
    echo "$site: rotated key $name"
  else
    secret="$(api POST /api-keys "$(jq -cn --arg n "$name" --arg s "$site" \
      '{name:$n, role:"api-worker", pools:[$s], description:("simulated site VM " + $s)}')" | jq -r .secret)"
    echo "$site: created key $name (scoped to pool $site)"
  fi

  umask 077
  env="$DIR/$site.env"
  cat >"$env" <<ENV
# Generated by sites/issue-keys.sh. This is what /etc/primeflow/worker.env holds
# on a real site VM, plus PRIMEFLOW_API_URL, which docker-compose.sites.yml
# supplies here (SITE_API_URL): a pool-scoped key and the lane it serves, nothing else.
PRIMEFLOW_WORKER_TOKEN=$secret
PRIMEFLOW_QUEUES=$site
PRIMEFLOW_WORKER_NAME=$site-vm1
PRIMEFLOW_CONCURRENCY=2
ENV
  echo "$site: wrote ${env#"$PWD/"}"
done
